language: node_js
node_js:
  - '0.10'
env:
  global:
    - NODE_ENV=travisci
before_script:
  - npm install -g grunt-cli
  - psql -c 'create database anime_tweet_test;' -U postgres
  - psql -U postgres -d 'anime_tweet_test' -c 'create table anime (id serial primary key, aria text unique not null, titles text);'
branches:
  only:
    - master
    - travis-settings
addons:
  postgresql: "9.3"
deploy:
  provider: heroku
  app: anime-tweet
  api_key:
    secure: PuRaHgQ08Ngj3gvg1AnPM2f6Z+js2GXmbQYAU16iSVMMp1/j85is8zcGN8lOHcPFN+ENy/Lauo9AF7FAgoOxiYdCzkYc5+H3ToQRtkRj9TYbfqwLHm0th0Mf96R5ccB7MO4n+NYhD/hCOKznQK6ssjssLPz06Cb0Qzs8yyrFWJk=
